#!/usr/bin/python3

# This script is used by the projects script to find all subdirectories
# containing header files in a directory. Can be used standalone as well.

import os
import sys


def IncludeRecursively(directory):
    # Include all directories containing a header file of some sort
    # recursively, without manually adding them in to the flags
    # list
    include_paths = []

    for root, subdirs, files in os.walk(directory):
        if os.path.basename(root) == 'include' and root not in include_paths:
            include_paths.append('-isystem')
            include_paths.append(root)

            continue

        for file in files:
            if '.h' in file and root not in include_paths:
                include_paths.append('-isystem')
                include_paths.append(root)

                break

    return include_paths


if __name__ == '__main__':
    project_dir = sys.argv[1]

    include_dirs = IncludeRecursively(project_dir)
    print(' '.join(include_dirs))
